spring.application.name=auth-service

server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/profinity-auth-service-db
spring.datasource.username=postgres
spring.datasource.password=abhijit@07

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

jwt.secret-key=${JWT_SECRET_KEY};
