spring:
  application:
    name: auth-service

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

  datasource:
    url: jdbc:postgresql://profinity-auth-service-db:5432/db
    username: admin
    password: abhijit@07

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 8001

jwt:
  secret-key: "jndkjnDKNknkdnsk94789jskanNDd3unksndf89ruProfinitysndfkjFsdjnfkDJNFJNkdqw9r"

