spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.type.mapping: userUpdate:com.profinity.userservice.event.UserEventRecord,connectionEvent:com.profinity.userservice.event.ConnectionRecord

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.type.mapping: userCreated:com.profinity.userservice.event.UserCreatedEvent #,postCreated:com.profinity.userservice.event.PostCreatedEvent
        spring.json.trusted.packages: com.profinity.userservice.event


  datasource:
    url: jdbc:postgresql://profinity-user-service-db:5432/db
    username: admin
    password: abhijit@07

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 8002